### ISSUE TITLE
Validate fails due to invalid path at file reader decorator

### ISSUE THREAD

**Issue by pmatos** [pmatos/jsc32-fuzz#1]
```
fuzzer_1  | Traceback (most recent call last):
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/controller.py", line 413, in _run_job
fuzzer_1  |     for issue in job.run():
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/job/validate_job.py", line 29, in run
fuzzer_1  |     _, new_issues = self.validate()
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/job/validate_job.py", line 37, in validate
fuzzer_1  |     issue = sut_call(**sut_call_kwargs)
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/config.py", line 42, in __call__
fuzzer_1  |     return self._callable(*args, **kwargs)
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/call/file_reader_decorator.py", line 41, in reader
fuzzer_1  |     with open(kwargs['test'], 'rb') as f:
fuzzer_1  | OSError: [Errno 36] File name too long: b'// Original: resources/stubs.js\nfunction nop() {\n  return false;\n}\n\ntry {\n  gc;\n} catch (e) {\n  this.gc = function () {\n    for (let i = 0; i < 10000; i++) {\n      let s = new String("AAAA" + Math.random());\n    }\n  };\n}\n\ntry {\n  uneval;\n} catch (e) {\n  this.uneval = this.nop;\n}\
```

I am uncertain why this is happening because we are writing the test to a file using the `FileWriterDecorator` before hand. So when we get `FileReaderDecorator`, `test` should be a filename. It is possible that https://github.com/renatahodovan/fuzzinator/pull/38 will fix it.

**Comment by pmatos** [comment]
Fixed in https://github.com/pmatos/jsc32-fuzz/commit/104f3d426369c144361a084ea98579ef7d149e35
